### ISSUE TITLE
Crash when i going to view post

### ISSUE THREAD

**Issue by LunarstarFurry** [auzbuzzard/project-derpi#2]
java.lang.NullPointerException: Attempt to read from field 'java.util.List derpibooru.derpy.data.server.DerpibooruImageDetailed.mFavedBy' on a null object reference
	at derpibooru.derpy.ui.fragments.imageactivity.tabs.ImageBottomBarFavoritesTabFragment.onCreateView(ImageBottomBarFavoritesTabFragment.java:1062)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate$52bc874c(FragmentStatePagerAdapter.java:164)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
	at android.support.v4.view.ViewPager.setAdapter(ViewPager.java:503)
	at derpibooru.derpy.ui.fragments.imageactivity.ImageActivityMainFragment.displayImageInRootView(ImageActivityMainFragment.java:7064)
	at derpibooru.derpy.ui.ImageActivity$2.onQueryExecuted(ImageActivity.java:2078)
	at derpibooru.derpy.server.providers.Provider$UiThreadMessageSender.run(Provider.java:62)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

Got this Error here

**Comment by auzbuzzard** [comment]
Can you describe what you did that cause the problem? Are you clicking onto an image or viewing the descriptions?

**Comment by LunarstarFurry** [comment]
viewing the descriptions
